### PR TITLE
Remote Peer, MTU and PersistentKeepalives added

### PR DESCRIPTION
**Pull request by reafian**
Kinda got carried away here. The Remote Peer is on the global settings page, the MTU and PersistentKeepalives are set on the peer config page. The settings also appear on the new peer page too.

The Remote Peer endpoint can be an IP, hostname or FQDN and it seems to work fine.

This covers issues #60, #61 and #62. You can probably find ways of making this much tidier.

### CODE REVIEW

**Comment by ricohard** [comment]
It's an awesome project. :-)

I'm no developer by any stretch of the imagination and I'm honestly surprised I got any of this working (first proper time trying to use GitHub too) but I'm running this locally now and it's doing its job. Pretty soon I'll end up completely out of my depth but I'll try and keep tweaking things for a while. I had this thought to try and make IPv6 addresses allowed alongside or instead of IPv4 but that might just break my little head.

**Comment by donaldzou** [comment]
Hi, I will manually merge your PR into the newest beta ;) Thank you so much for doing this!

**Comment by reafian** [comment]
That's cool. You know how you want things to work so do whatever you think is best.

**Comment by donaldzou** [comment]
@all-contributors please add @reafian  for code

**Review by donaldzou — APPROVED** [review]

**Comment by donaldzou** [comment]
I’ve successfully merged your code into the next release ;)

**Pull request closed without merging**
